language: objective-c
osx_image: xcode8.3
env:
  global:
  - FRAMEWORK_NAME=VectorMath
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
script: xcodebuild test -scheme VectorMath_macOS -sdk macosx10.12
before_deploy:
- "./CarthageScripts/build-static-framework.sh"
- carthage archive $FRAMEWORK_NAME
deploy:
  provider: releases
  api_key:
    secure: kYfXQ0NfJBycvEfSF5yq8YdHZJp/hCOqFLyWu8VvacKHYY4NeRUo66RKUt3GlsmeAgMdyMcRojAOVK4iR3KOUXCnlDMe3thPbg0LHIcs45KDGPTRmsOUCHWNVQJ6sV/gI2xaH8P+Ony+Q4vVmAW4DY9T/yq5VXHTm5KIP8CZcqJ6tEeMsYCFQzbq92AKsxPT4TDmDC5J0aabqOP3vRPUj/UNN6W/HRqNcZpkF3Fg+U6eqjEDcgiQ0A+yzOzKr8T4eLvrwqjqXpj2+nw+RmhhfGv9dhn4+PWhqcEAXTFMGda1zu1C385uSClJEdGXYnpoz1WMj5ylvqYx6iIBC405L9CTQD33jSaQrI1nqtajNTdxm8IiTiWKp/vjHzXKjzaYZR3VzH1PsaQvtohMoX+6AO9K22uFA8mWVkODI1k7lJeR5RRwj3Ev8XyxKoSQKmA44i1JpXec+o4x9gW8DEySYJrZHV0PFVjl2vTzjqLyMPEhrhaiJ3tSH0mml8yz8zdJnTtQFulhYzCSY9XrEea4n3TyNyspNcKz2fjZacIjmprT4rFZBU0tFzulj4U1B9N4PIE2BPI8LuWMhJWmVelEyafvi0PqL6mrtl126AYdGoUfrHS/iJ75ZB2Ae0I/vq82r6rRJqVmZ7am0oWLjafDS4UTnBVCUWNBUNew1WRyC0w=
  file: "$FRAMEWORK_NAME.framework.zip"
  skip_cleanup: true
  on:
    repo: flinto/VectorMath
    tags: true

